/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Kev
 */
public class DrawSelect extends javax.swing.JFrame {

    /**
     * Creates new form DrawSelect
     */
    public DrawSelect() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTitle = new javax.swing.JLabel();
        jWelcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLotto = new javax.swing.JButton();
        jLottoPlus = new javax.swing.JButton();
        jDraw1Header = new javax.swing.JLabel();
        jDrawHeader2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(715, 425, 425, 425));
        setMaximumSize(new java.awt.Dimension(715, 425));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(691, 393));

        jTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/lottoimg.gif"))); // NOI18N

        jWelcome.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jWelcome.setText("Welcome to the National Lottery, Would you like to play?  ");

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel1.setText("Please select which draw you wish to enter");

        jLotto.setBackground(new java.awt.Color(102, 255, 0));
        jLotto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/Lotto.png"))); // NOI18N
        jLotto.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jLotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLottoActionPerformed(evt);
            }
        });

        jLottoPlus.setBackground(new java.awt.Color(51, 102, 255));
        jLottoPlus.setForeground(new java.awt.Color(255, 255, 255));
        jLottoPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/Lotto-plus-2.jpg"))); // NOI18N
        jLottoPlus.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jLottoPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLottoPlusActionPerformed(evt);
            }
        });

        jDraw1Header.setFont(new java.awt.Font("Imprint MT Shadow", 0, 12)); // NOI18N
        jDraw1Header.setForeground(new java.awt.Color(255, 0, 0));
        jDraw1Header.setText("Click to plsy the draw Lotto");

        jDrawHeader2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 12)); // NOI18N
        jDrawHeader2.setForeground(new java.awt.Color(255, 0, 0));
        jDrawHeader2.setText("Click to play draws Lotto, Plus1 & Plus2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jWelcome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLotto)
                                    .addComponent(jDraw1Header))
                                .addGap(137, 137, 137)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDrawHeader2)
                                    .addComponent(jLottoPlus)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jTitle)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitle)
                .addGap(18, 18, 18)
                .addComponent(jWelcome)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDraw1Header)
                    .addComponent(jDrawHeader2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLottoPlus)
                    .addComponent(jLotto))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLottoPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLottoPlusActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LottoPlus().setVisible(true);
    }//GEN-LAST:event_jLottoPlusActionPerformed

    private void jLottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLottoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Lotto().setVisible(true);
    }//GEN-LAST:event_jLottoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDraw1Header;
    private javax.swing.JLabel jDrawHeader2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLotto;
    private javax.swing.JButton jLottoPlus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTitle;
    private javax.swing.JLabel jWelcome;
    // End of variables declaration//GEN-END:variables
}
