/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Arrays;

/**
 *
 * @author x14105586
 */
public class Lotto extends javax.swing.JFrame {

    /**
     * Creates new form FirstLottery
     */
    public Lotto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTitle = new javax.swing.JLabel();
        jLotto = new javax.swing.JLabel();
        jGoBack = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jL1 = new javax.swing.JLabel();
        jL1N1 = new javax.swing.JTextField();
        jL1N2 = new javax.swing.JTextField();
        jL1N3 = new javax.swing.JTextField();
        jL1N4 = new javax.swing.JTextField();
        jL1N5 = new javax.swing.JTextField();
        jL2 = new javax.swing.JLabel();
        jL2N1 = new javax.swing.JTextField();
        jL2N2 = new javax.swing.JTextField();
        jL2N3 = new javax.swing.JTextField();
        jL2N4 = new javax.swing.JTextField();
        jL2N5 = new javax.swing.JTextField();
        jL3 = new javax.swing.JLabel();
        jL3N1 = new javax.swing.JTextField();
        jL3N2 = new javax.swing.JTextField();
        jL3N3 = new javax.swing.JTextField();
        jL3N4 = new javax.swing.JTextField();
        jL3N5 = new javax.swing.JTextField();
        jSubmit = new javax.swing.JButton();
        jDrawNum = new javax.swing.JTextField();
        jResult = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMessage = new javax.swing.JTextField();
        jLine1 = new javax.swing.JTextField();
        jLine2 = new javax.swing.JTextField();
        jLine3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(715, 425, 425, 425));
        setMaximumSize(new java.awt.Dimension(715, 425));
        setMinimumSize(new java.awt.Dimension(715, 425));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 0), 2, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(715, 515));
        jPanel1.setMinimumSize(new java.awt.Dimension(715, 515));

        jTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/lottoimg.gif"))); // NOI18N

        jLotto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/Lotto.png"))); // NOI18N

        jGoBack.setFont(new java.awt.Font("Imprint MT Shadow", 0, 11)); // NOI18N
        jGoBack.setText("Go Back");

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel4.setText("Please enter your numbers in each line");

        jL1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jL1.setText("Line 1");

        jL1N1.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL1N1.setMaximumSize(new java.awt.Dimension(5, 25));
        jL1N1.setMinimumSize(new java.awt.Dimension(5, 25));
        jL1N1.setPreferredSize(new java.awt.Dimension(5, 25));

        jL1N2.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL1N2.setMaximumSize(new java.awt.Dimension(5, 25));
        jL1N2.setMinimumSize(new java.awt.Dimension(5, 25));
        jL1N2.setPreferredSize(new java.awt.Dimension(5, 25));

        jL1N3.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL1N3.setPreferredSize(new java.awt.Dimension(5, 25));

        jL1N4.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL1N4.setPreferredSize(new java.awt.Dimension(5, 25));

        jL1N5.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL1N5.setPreferredSize(new java.awt.Dimension(5, 25));

        jL2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jL2.setText("Line 2");

        jL2N1.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL2N1.setMaximumSize(new java.awt.Dimension(5, 25));
        jL2N1.setMinimumSize(new java.awt.Dimension(5, 25));
        jL2N1.setPreferredSize(new java.awt.Dimension(5, 25));

        jL2N2.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL2N2.setMaximumSize(new java.awt.Dimension(5, 25));
        jL2N2.setMinimumSize(new java.awt.Dimension(5, 25));
        jL2N2.setPreferredSize(new java.awt.Dimension(5, 25));

        jL2N3.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL2N3.setMaximumSize(new java.awt.Dimension(5, 25));
        jL2N3.setMinimumSize(new java.awt.Dimension(5, 25));
        jL2N3.setPreferredSize(new java.awt.Dimension(5, 25));

        jL2N4.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL2N4.setMaximumSize(new java.awt.Dimension(5, 25));
        jL2N4.setMinimumSize(new java.awt.Dimension(5, 25));
        jL2N4.setPreferredSize(new java.awt.Dimension(5, 25));

        jL2N5.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL2N5.setMaximumSize(new java.awt.Dimension(5, 25));
        jL2N5.setMinimumSize(new java.awt.Dimension(5, 25));
        jL2N5.setPreferredSize(new java.awt.Dimension(5, 25));

        jL3.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jL3.setText("Line 3");

        jL3N1.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL3N1.setMaximumSize(new java.awt.Dimension(5, 25));
        jL3N1.setMinimumSize(new java.awt.Dimension(5, 25));
        jL3N1.setPreferredSize(new java.awt.Dimension(5, 25));

        jL3N2.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL3N2.setMaximumSize(new java.awt.Dimension(5, 25));
        jL3N2.setMinimumSize(new java.awt.Dimension(5, 25));
        jL3N2.setPreferredSize(new java.awt.Dimension(5, 25));
        jL3N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL3N2ActionPerformed(evt);
            }
        });

        jL3N3.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL3N3.setMaximumSize(new java.awt.Dimension(5, 25));
        jL3N3.setMinimumSize(new java.awt.Dimension(5, 25));
        jL3N3.setPreferredSize(new java.awt.Dimension(5, 25));

        jL3N4.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL3N4.setMaximumSize(new java.awt.Dimension(5, 25));
        jL3N4.setMinimumSize(new java.awt.Dimension(5, 25));
        jL3N4.setPreferredSize(new java.awt.Dimension(5, 25));

        jL3N5.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL3N5.setMaximumSize(new java.awt.Dimension(5, 25));
        jL3N5.setMinimumSize(new java.awt.Dimension(5, 25));
        jL3N5.setPreferredSize(new java.awt.Dimension(5, 25));

        jSubmit.setBackground(new java.awt.Color(102, 255, 0));
        jSubmit.setText("Submit");
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });

        jDrawNum.setBorder(null);
        jDrawNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDrawNumActionPerformed(evt);
            }
        });

        jResult.setBorder(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/backlottoplus.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMessage.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jMessage.setForeground(new java.awt.Color(255, 0, 0));
        jMessage.setBorder(null);

        jLine1.setEditable(false);
        jLine1.setBackground(new java.awt.Color(255, 255, 255));
        jLine1.setBorder(null);

        jLine2.setEditable(false);
        jLine2.setBackground(new java.awt.Color(255, 255, 255));
        jLine2.setBorder(null);

        jLine3.setEditable(false);
        jLine3.setBackground(new java.awt.Color(255, 255, 255));
        jLine3.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSubmit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jL3N1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL3N2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL3N3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL3N4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jL2N4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jL1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jL1N1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jL1N2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jL1N3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jL1N4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jL2N1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL2N2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL2N3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jL1N5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                    .addComponent(jL2N5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jL3N5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jResult, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(jLine3)
                    .addComponent(jLine2)
                    .addComponent(jDrawNum)
                    .addComponent(jLine1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGoBack)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLotto)))
                .addGap(0, 90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLotto)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addComponent(jTitle))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jGoBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL1N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL1N2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL1N3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL1N4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL1N5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL1)
                            .addComponent(jLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jL2)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jL2N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jL2N2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jL2N3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jL2N4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jL2N5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL3)
                    .addComponent(jL3N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL3N2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL3N3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL3N4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL3N5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSubmit)
                    .addComponent(jDrawNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jL3N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL3N2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL3N2ActionPerformed

    private void jDrawNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDrawNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDrawNumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DrawSelect().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
        // TODO add your handling code here:
        int l1n1, l1n2, l1n3, l1n4, l1n5;
        int l2n1, l2n2, l2n3, l2n4, l2n5;
        int l3n1, l3n2, l3n3, l3n4, l3n5;
        int SecretNum[], count1, count2, count3;
        SecretNum = new int[5];
        count1 = 0;
        count2 = 0;
        count3 = 0;
        
        String l1n1String, l1n2String, l1n3String, l1n4String, l1n5String;
        String l2n1String, l2n2String, l2n3String, l2n4String, l2n5String;
        String l3n1String, l3n2String, l3n3String, l3n4String, l3n5String;
        
        l1n1String = jL1N1.getText();
        l1n2String = jL1N2.getText();
        l1n3String = jL1N3.getText();
        l1n4String = jL1N4.getText();
        l1n5String = jL1N5.getText();
        
        l2n1String = jL2N1.getText();
        l2n2String = jL2N2.getText();
        l2n3String = jL2N3.getText();
        l2n4String = jL2N4.getText();
        l2n5String = jL2N5.getText();
        
        l3n1String = jL3N1.getText();
        l3n2String = jL3N2.getText();
        l3n3String = jL3N3.getText();
        l3n4String = jL3N4.getText();
        l3n5String = jL3N5.getText();
        
        l1n1 = Integer.parseInt(l1n1String);
        l1n2 = Integer.parseInt(l1n2String);
        l1n3 = Integer.parseInt(l1n3String);
        l1n4 = Integer.parseInt(l1n4String);
        l1n5 = Integer.parseInt(l1n5String);
        
        l2n1 = Integer.parseInt(l2n1String);
        l2n2 = Integer.parseInt(l2n2String);
        l2n3 = Integer.parseInt(l2n3String);
        l2n4 = Integer.parseInt(l2n4String);
        l2n5 = Integer.parseInt(l2n5String);
        
        l3n1 = Integer.parseInt(l3n1String);
        l3n2 = Integer.parseInt(l3n2String);
        l3n3 = Integer.parseInt(l3n3String);
        l3n4 = Integer.parseInt(l3n4String);
        l3n5 = Integer.parseInt(l3n5String);
        
        if(l1n1==l1n2){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l1n3==l1n2||l1n3==l1n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l1n4==l1n3||l1n4==l1n2||l1n4==l1n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l1n5==l1n4||l1n5==l1n3||l1n5==l1n2||l1n5==l1n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l2n1==l2n2){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l2n3==l2n2||l2n3==l2n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l2n4==l2n3||l2n4==l2n2||l2n4==l2n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l2n5==l2n4||l2n5==l2n3||l2n5==l2n2||l2n5==l2n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l3n1==l3n2){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l3n3==l3n2||l3n3==l3n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l3n4==l3n3||l3n4==l3n2||l3n4==l3n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l3n5==l3n4||l3n5==l3n3||l3n5==l3n2||l3n5==l3n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else{
        
        outer:      for(int i=0; i<5; i++){
                        SecretNum[i]=(int)(Math.random()*40+1);
                        for(int j=0; j<i; j++){
                            if(SecretNum[i]==SecretNum[j]){
                                i--;
                                continue outer;
                            }
                        }
                    }
        
        for( int i=0; i<5; i++){
                if( l1n1 == SecretNum[i] || l1n2 == SecretNum[i] || l1n3 == SecretNum[i] || l1n4 == SecretNum[i] || l1n5 == SecretNum[i]){
                    count1++;
                
                }
            }
        
        for( int i=0; i<5; i++){
                if( l2n1 == SecretNum[i] || l2n2 == SecretNum[i] || l2n3 == SecretNum[i] || l2n4 == SecretNum[i] || l2n5 == SecretNum[i]){
                    count2++;
                
                }
            }
        
        for( int i=0; i<5; i++){
                if( l3n1 == SecretNum[i] || l3n2 == SecretNum[i] || l3n3 == SecretNum[i] || l3n4 == SecretNum[i] || l3n5 == SecretNum[i]){
                    count3++;
                
                }
            }
        
        jDrawNum.setText("The draw numbers were: "+Arrays.toString(SecretNum));
        
        jLine1.setText("You matched "+count1+" Numbers in line 1");
        jLine2.setText("You matched "+count2+" Numbers in line 2");
        jLine3.setText("You matched "+count3+" Numbers in line 3");
        
        jMessage.setText("Click the green arrow at the corner of the screen to play again!");
       
        for(int i=0;i<4;i++){
        if(count1==2 || count2==2 || count3==2){
            jResult.setText("congratulations! You win €1,000");
            
        }
        else if(count1==3 || count2==3 || count3==3){
            jResult.setText("congratulations! You win €10,000");
            
        }
        else if(count1==4 || count2==4 || count3==4){
            jResult.setText("congratulations! You win €100,000");
            
        }
        else if(count1==5 || count2==5 || count3==5){
            jResult.setText("congratulations! You win €1,000,000");
            
        }
        
        else{
            jResult.setText("No prizes this time, please try again");
        }
        }
        }
        
    }//GEN-LAST:event_jSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lotto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lotto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lotto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lotto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lotto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jDrawNum;
    private javax.swing.JLabel jGoBack;
    private javax.swing.JLabel jL1;
    private javax.swing.JTextField jL1N1;
    private javax.swing.JTextField jL1N2;
    private javax.swing.JTextField jL1N3;
    private javax.swing.JTextField jL1N4;
    private javax.swing.JTextField jL1N5;
    private javax.swing.JLabel jL2;
    private javax.swing.JTextField jL2N1;
    private javax.swing.JTextField jL2N2;
    private javax.swing.JTextField jL2N3;
    private javax.swing.JTextField jL2N4;
    private javax.swing.JTextField jL2N5;
    private javax.swing.JLabel jL3;
    private javax.swing.JTextField jL3N1;
    private javax.swing.JTextField jL3N2;
    private javax.swing.JTextField jL3N3;
    private javax.swing.JTextField jL3N4;
    private javax.swing.JTextField jL3N5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jLine1;
    private javax.swing.JTextField jLine2;
    private javax.swing.JTextField jLine3;
    private javax.swing.JLabel jLotto;
    private javax.swing.JTextField jMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jResult;
    private javax.swing.JButton jSubmit;
    private javax.swing.JLabel jTitle;
    // End of variables declaration//GEN-END:variables
}
