/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import java.util.ArrayList;
/**
 *
 * @author x14105586
 */
public class LottoGUI extends javax.swing.JFrame {

    private int l1n1, l1n2, l1n3, l1n4, l1n5;
    private int l2n1, l2n2, l2n3, l2n4, l2n5;
    private int l3n1, l3n2, l3n3, l3n4, l3n5;
    private int listNum;
    private int SecretNum[], count1, count2, count3, count;
    private String l1n1String, l1n2String, l1n3String, l1n4String, l1n5String;
    private String l2n1String, l2n2String, l2n3String, l2n4String, l2n5String;
    private String l3n1String, l3n2String, l3n3String, l3n4String, l3n5String;
    private ArrayList <Lotto> aList;
        
    public LottoGUI() {
        initComponents();
        SecretNum = new int[5];
        count = 0;
        aList = new ArrayList<>();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTitle = new javax.swing.JLabel();
        jLotto = new javax.swing.JLabel();
        jGoBack = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jL1 = new javax.swing.JLabel();
        jL1N1 = new javax.swing.JTextField();
        jL1N2 = new javax.swing.JTextField();
        jL1N3 = new javax.swing.JTextField();
        jL1N4 = new javax.swing.JTextField();
        jL1N5 = new javax.swing.JTextField();
        jL2 = new javax.swing.JLabel();
        jL2N1 = new javax.swing.JTextField();
        jL2N2 = new javax.swing.JTextField();
        jL2N3 = new javax.swing.JTextField();
        jL2N4 = new javax.swing.JTextField();
        jL2N5 = new javax.swing.JTextField();
        jL3 = new javax.swing.JLabel();
        jL3N1 = new javax.swing.JTextField();
        jL3N2 = new javax.swing.JTextField();
        jL3N3 = new javax.swing.JTextField();
        jL3N4 = new javax.swing.JTextField();
        jL3N5 = new javax.swing.JTextField();
        jSubmit = new javax.swing.JButton();
        jDrawNum = new javax.swing.JTextField();
        jResult = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMessage = new javax.swing.JTextField();
        jLine1 = new javax.swing.JTextField();
        jLine2 = new javax.swing.JTextField();
        jLine3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        Compareold = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        upgrade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(715, 425, 425, 425));
        setMaximumSize(new java.awt.Dimension(715, 425));
        setMinimumSize(new java.awt.Dimension(715, 425));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 0), 2, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(715, 515));
        jPanel1.setMinimumSize(new java.awt.Dimension(715, 515));

        jTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/lottoimg.gif"))); // NOI18N

        jLotto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/Lotto.png"))); // NOI18N

        jGoBack.setFont(new java.awt.Font("Imprint MT Shadow", 0, 11)); // NOI18N
        jGoBack.setText("Go Back");

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel4.setText("Please enter your numbers in each line");

        jL1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jL1.setText("Line 1");

        jL1N1.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL1N1.setMaximumSize(new java.awt.Dimension(5, 25));
        jL1N1.setMinimumSize(new java.awt.Dimension(5, 25));
        jL1N1.setPreferredSize(new java.awt.Dimension(5, 25));

        jL1N2.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL1N2.setMaximumSize(new java.awt.Dimension(5, 25));
        jL1N2.setMinimumSize(new java.awt.Dimension(5, 25));
        jL1N2.setPreferredSize(new java.awt.Dimension(5, 25));

        jL1N3.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL1N3.setPreferredSize(new java.awt.Dimension(5, 25));

        jL1N4.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL1N4.setPreferredSize(new java.awt.Dimension(5, 25));

        jL1N5.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL1N5.setPreferredSize(new java.awt.Dimension(5, 25));

        jL2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jL2.setText("Line 2");

        jL2N1.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL2N1.setMaximumSize(new java.awt.Dimension(5, 25));
        jL2N1.setMinimumSize(new java.awt.Dimension(5, 25));
        jL2N1.setPreferredSize(new java.awt.Dimension(5, 25));

        jL2N2.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL2N2.setMaximumSize(new java.awt.Dimension(5, 25));
        jL2N2.setMinimumSize(new java.awt.Dimension(5, 25));
        jL2N2.setPreferredSize(new java.awt.Dimension(5, 25));

        jL2N3.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL2N3.setMaximumSize(new java.awt.Dimension(5, 25));
        jL2N3.setMinimumSize(new java.awt.Dimension(5, 25));
        jL2N3.setPreferredSize(new java.awt.Dimension(5, 25));

        jL2N4.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL2N4.setMaximumSize(new java.awt.Dimension(5, 25));
        jL2N4.setMinimumSize(new java.awt.Dimension(5, 25));
        jL2N4.setPreferredSize(new java.awt.Dimension(5, 25));

        jL2N5.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL2N5.setMaximumSize(new java.awt.Dimension(5, 25));
        jL2N5.setMinimumSize(new java.awt.Dimension(5, 25));
        jL2N5.setPreferredSize(new java.awt.Dimension(5, 25));

        jL3.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jL3.setText("Line 3");

        jL3N1.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL3N1.setMaximumSize(new java.awt.Dimension(5, 25));
        jL3N1.setMinimumSize(new java.awt.Dimension(5, 25));
        jL3N1.setPreferredSize(new java.awt.Dimension(5, 25));

        jL3N2.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL3N2.setMaximumSize(new java.awt.Dimension(5, 25));
        jL3N2.setMinimumSize(new java.awt.Dimension(5, 25));
        jL3N2.setPreferredSize(new java.awt.Dimension(5, 25));
        jL3N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL3N2ActionPerformed(evt);
            }
        });

        jL3N3.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL3N3.setMaximumSize(new java.awt.Dimension(5, 25));
        jL3N3.setMinimumSize(new java.awt.Dimension(5, 25));
        jL3N3.setPreferredSize(new java.awt.Dimension(5, 25));

        jL3N4.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL3N4.setMaximumSize(new java.awt.Dimension(5, 25));
        jL3N4.setMinimumSize(new java.awt.Dimension(5, 25));
        jL3N4.setPreferredSize(new java.awt.Dimension(5, 25));

        jL3N5.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jL3N5.setMaximumSize(new java.awt.Dimension(5, 25));
        jL3N5.setMinimumSize(new java.awt.Dimension(5, 25));
        jL3N5.setPreferredSize(new java.awt.Dimension(5, 25));

        jSubmit.setBackground(new java.awt.Color(102, 255, 0));
        jSubmit.setText("Submit");
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });

        jDrawNum.setBorder(null);
        jDrawNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDrawNumActionPerformed(evt);
            }
        });

        jResult.setBorder(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/backlottoplus.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMessage.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jMessage.setForeground(new java.awt.Color(255, 0, 0));
        jMessage.setBorder(null);

        jLine1.setEditable(false);
        jLine1.setBackground(new java.awt.Color(255, 255, 255));
        jLine1.setBorder(null);

        jLine2.setEditable(false);
        jLine2.setBackground(new java.awt.Color(255, 255, 255));
        jLine2.setBorder(null);

        jLine3.setEditable(false);
        jLine3.setBackground(new java.awt.Color(255, 255, 255));
        jLine3.setBorder(null);

        saveBtn.setBackground(new java.awt.Color(102, 255, 0));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        viewBtn.setBackground(new java.awt.Color(102, 255, 0));
        viewBtn.setText("View Save");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        Compareold.setBackground(new java.awt.Color(102, 255, 0));
        Compareold.setText("Compare the old");
        Compareold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompareoldActionPerformed(evt);
            }
        });

        Add.setBackground(new java.awt.Color(102, 255, 0));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        upgrade.setBackground(new java.awt.Color(102, 255, 0));
        upgrade.setText("Update");
        upgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upgradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jL1N1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL1N2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL1N3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL1N4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jL2N1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL2N2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL2N3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jL3N1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jL2N4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jL3N2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jL3N3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jL3N4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 9, Short.MAX_VALUE)))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jL1N5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                    .addComponent(jL2N5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jL3N5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(Compareold, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(33, 33, 33)
                                .addComponent(upgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jResult, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(jLine3)
                    .addComponent(jLine2)
                    .addComponent(jDrawNum)
                    .addComponent(jLine1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGoBack)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLotto)))
                .addGap(0, 148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(upgrade))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLotto)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1)
                                        .addComponent(jTitle))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jGoBack)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jL1N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL1N2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL1N3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL1N4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL1N5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL1)
                                    .addComponent(jLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jL2)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jL2N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jL2N2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jL2N3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jL2N4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jL2N5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL3)
                            .addComponent(jL3N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL3N2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL3N3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL3N4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL3N5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDrawNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Add)
                                .addComponent(viewBtn)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(Compareold, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jL3N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL3N2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL3N2ActionPerformed

    private void jDrawNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDrawNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDrawNumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DrawSelectGUI().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
        // TODO add your handling code here:
        l1n1String = jL1N1.getText();
        l1n2String = jL1N2.getText();
        l1n3String = jL1N3.getText();
        l1n4String = jL1N4.getText();
        l1n5String = jL1N5.getText();
        
        l2n1String = jL2N1.getText();
        l2n2String = jL2N2.getText();
        l2n3String = jL2N3.getText();
        l2n4String = jL2N4.getText();
        l2n5String = jL2N5.getText();
        
        l3n1String = jL3N1.getText();
        l3n2String = jL3N2.getText();
        l3n3String = jL3N3.getText();
        l3n4String = jL3N4.getText();
        l3n5String = jL3N5.getText();
        
        count1 = 0;
        count2 = 0;
        count3 = 0;
        
        l1n1 = Integer.parseInt(l1n1String);
        l1n2 = Integer.parseInt(l1n2String);
        l1n3 = Integer.parseInt(l1n3String);
        l1n4 = Integer.parseInt(l1n4String);
        l1n5 = Integer.parseInt(l1n5String);
        
        l2n1 = Integer.parseInt(l2n1String);
        l2n2 = Integer.parseInt(l2n2String);
        l2n3 = Integer.parseInt(l2n3String);
        l2n4 = Integer.parseInt(l2n4String);
        l2n5 = Integer.parseInt(l2n5String);
        
        l3n1 = Integer.parseInt(l3n1String);
        l3n2 = Integer.parseInt(l3n2String);
        l3n3 = Integer.parseInt(l3n3String);
        l3n4 = Integer.parseInt(l3n4String);
        l3n5 = Integer.parseInt(l3n5String);
        
        if(l1n1==l1n2){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l1n3==l1n2||l1n3==l1n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l1n4==l1n3||l1n4==l1n2||l1n4==l1n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l1n5==l1n4||l1n5==l1n3||l1n5==l1n2||l1n5==l1n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l2n1==l2n2){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l2n3==l2n2||l2n3==l2n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l2n4==l2n3||l2n4==l2n2||l2n4==l2n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l2n5==l2n4||l2n5==l2n3||l2n5==l2n2||l2n5==l2n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l3n1==l3n2){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l3n3==l3n2||l3n3==l3n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l3n4==l3n3||l3n4==l3n2||l3n4==l3n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l3n5==l3n4||l3n5==l3n3||l3n5==l3n2||l3n5==l3n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else{
        
        outer:      for(int i=0; i<5; i++){
                        SecretNum[i]=(int)(Math.random()*40+1);
                        for(int j=0; j<i; j++){
                            if(SecretNum[i]==SecretNum[j]){
                                i--;
                                continue outer;
                            }
                        }
                    }
        
        for( int i=0; i<5; i++){
                if( l1n1 == SecretNum[i] || l1n2 == SecretNum[i] || l1n3 == SecretNum[i] || l1n4 == SecretNum[i] || l1n5 == SecretNum[i]){
                    count1++;
                
                }
            }
        
        for( int i=0; i<5; i++){
                if( l2n1 == SecretNum[i] || l2n2 == SecretNum[i] || l2n3 == SecretNum[i] || l2n4 == SecretNum[i] || l2n5 == SecretNum[i]){
                    count2++;
                
                }
            }
        
        for( int i=0; i<5; i++){
                if( l3n1 == SecretNum[i] || l3n2 == SecretNum[i] || l3n3 == SecretNum[i] || l3n4 == SecretNum[i] || l3n5 == SecretNum[i]){
                    count3++;
                
                }
            }
        
        jDrawNum.setText("The draw numbers were: "+Arrays.toString(SecretNum));
        
        jLine1.setText("You matched "+count1+" Numbers in line 1");
        jLine2.setText("You matched "+count2+" Numbers in line 2");
        jLine3.setText("You matched "+count3+" Numbers in line 3");
        
        jMessage.setText("Click the green arrow at the corner of the screen to play again!");
       
        for(int i=0;i<4;i++){
        if(count1==2 || count2==2 || count3==2){
            jResult.setText("congratulations! You win €1,000");
            
        }
        else if(count1==3 || count2==3 || count3==3){
            jResult.setText("congratulations! You win €10,000");
            
        }
        else if(count1==4 || count2==4 || count3==4){
            jResult.setText("congratulations! You win €100,000");
            
        }
        else if(count1==5 || count2==5 || count3==5){
            jResult.setText("congratulations! You win €1,000,000");
            
        }
        
        else{
            jResult.setText("No prizes this time, please try again");
        }
        }
        }
        
    }//GEN-LAST:event_jSubmitActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

        File OutFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        
        try{
            OutFile= new File("Output.data");
            fStream= new FileOutputStream(OutFile);
            oStream=new ObjectOutputStream(fStream);
            
            oStream.writeObject(aList);
            
            JOptionPane.showMessageDialog(null,"File written successfully.");
            
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
            
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("Output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            ArrayList <Lotto> yList;
            yList = (ArrayList<Lotto>)oStream.readObject();
            for(Lotto y:yList){
                    JOptionPane.showMessageDialog(null,"Line1: "+y.getL1n1()+", "+y.getL1n2()+", "+y.getL1n3()+", "+y.getL1n4()+", "+y.getL1n5()+", "+"Line2: "+y.getL2n1()+", "+y.getL2n2()+", "+y.getL2n3()+", "+y.getL2n4()+", "+y.getL2n5()+", "+"Line3: "+y.getL3n1()+", "+y.getL3n2()+", "+y.getL3n3()+", "+y.getL3n4()+", "+y.getL3n5());
                }
            
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
            
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
            
        
        
        
        
    }//GEN-LAST:event_viewBtnActionPerformed

    private void CompareoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompareoldActionPerformed
        // TODO add your handling code here:
        count1 = 0;
        count2 = 0;
        count3 = 0;
        listNum = 0;
        
        outer:      for(int i=0; i<5; i++){
                        SecretNum[i]=(int)(Math.random()*40+1);
                        for(int j=0; j<i; j++){
                            if(SecretNum[i]==SecretNum[j]){
                                i--;
                                continue outer;
                            }
                        }
                    }
        
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("Output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            ArrayList <Lotto> yList;
            yList = (ArrayList<Lotto>)oStream.readObject();
            
            listNum = Integer.parseInt(JOptionPane.showInputDialog(null,"You have already add "+yList.size()+" old input, Which one you want to choose? Please enter the number and click the 'OK' Button to continue!"));
            
                for( int i=0; i<5; i++){
                if( yList.get(listNum-1).getL1n1() == SecretNum[i] || yList.get(listNum-1).getL1n2() == SecretNum[i] || yList.get(listNum-1).getL1n3() == SecretNum[i] || yList.get(listNum-1).getL1n4() == SecretNum[i] || yList.get(listNum-1).getL1n5() == SecretNum[i]){
                    count1++;
                
                    }
                }
        
                for( int i=0; i<5; i++){
                if( yList.get(listNum-1).getL2n1() == SecretNum[i] || yList.get(listNum-1).getL2n2() == SecretNum[i] || yList.get(listNum-1).getL2n3() == SecretNum[i] || yList.get(listNum-1).getL2n4() == SecretNum[i] || yList.get(listNum-1).getL2n5() == SecretNum[i]){
                    count2++;
                
                    }
                }
        
                for( int i=0; i<5; i++){
                if( yList.get(listNum-1).getL3n1() == SecretNum[i] || yList.get(listNum-1).getL3n2() == SecretNum[i] || yList.get(listNum-1).getL3n3() == SecretNum[i] || yList.get(listNum-1).getL3n4() == SecretNum[i] || yList.get(listNum-1).getL3n5() == SecretNum[i]){
                    count3++;
                
                }
            }
        
            jDrawNum.setText("The draw numbers were: "+Arrays.toString(SecretNum));
        
            jLine1.setText("You matched "+count1+" Numbers in line 1");
            jLine2.setText("You matched "+count2+" Numbers in line 2");
            jLine3.setText("You matched "+count3+" Numbers in line 3");
        
            jMessage.setText("Click the green arrow at the corner of the screen to play again!");
       
            for(int i=0;i<4;i++){
            if(count1==2 || count2==2 || count3==2){
                jResult.setText("congratulations! You win €1,000");
            
            }
            else if(count1==3 || count2==3 || count3==3){
                jResult.setText("congratulations! You win €10,000");
            
            }
            else if(count1==4 || count2==4 || count3==4){
                jResult.setText("congratulations! You win €100,000");
            
            }
            else if(count1==5 || count2==5 || count3==5){
                jResult.setText("congratulations! You win €1,000,000");
            
            }
        
            else{
                jResult.setText("No prizes this time, please try again");
            }
            }
            
            
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
            
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_CompareoldActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        l1n1String = jL1N1.getText();
        l1n2String = jL1N2.getText();
        l1n3String = jL1N3.getText();
        l1n4String = jL1N4.getText();
        l1n5String = jL1N5.getText();
        
        l2n1String = jL2N1.getText();
        l2n2String = jL2N2.getText();
        l2n3String = jL2N3.getText();
        l2n4String = jL2N4.getText();
        l2n5String = jL2N5.getText();
        
        l3n1String = jL3N1.getText();
        l3n2String = jL3N2.getText();
        l3n3String = jL3N3.getText();
        l3n4String = jL3N4.getText();
        l3n5String = jL3N5.getText();
        
        l1n1 = Integer.parseInt(l1n1String);
        l1n2 = Integer.parseInt(l1n2String);
        l1n3 = Integer.parseInt(l1n3String);
        l1n4 = Integer.parseInt(l1n4String);
        l1n5 = Integer.parseInt(l1n5String);
        
        l2n1 = Integer.parseInt(l2n1String);
        l2n2 = Integer.parseInt(l2n2String);
        l2n3 = Integer.parseInt(l2n3String);
        l2n4 = Integer.parseInt(l2n4String);
        l2n5 = Integer.parseInt(l2n5String);
        
        l3n1 = Integer.parseInt(l3n1String);
        l3n2 = Integer.parseInt(l3n2String);
        l3n3 = Integer.parseInt(l3n3String);
        l3n4 = Integer.parseInt(l3n4String);
        l3n5 = Integer.parseInt(l3n5String);
        
        if(l1n1==l1n2){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l1n3==l1n2||l1n3==l1n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l1n4==l1n3||l1n4==l1n2||l1n4==l1n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l1n5==l1n4||l1n5==l1n3||l1n5==l1n2||l1n5==l1n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l2n1==l2n2){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l2n3==l2n2||l2n3==l2n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l2n4==l2n3||l2n4==l2n2||l2n4==l2n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l2n5==l2n4||l2n5==l2n3||l2n5==l2n2||l2n5==l2n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l3n1==l3n2){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l3n3==l3n2||l3n3==l3n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l3n4==l3n3||l3n4==l3n2||l3n4==l3n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else if(l3n5==l3n4||l3n5==l3n3||l3n5==l3n2||l3n5==l3n1){
            jMessage.setText("Please do not enter the same number in one Line!");
        }
        else{
        
        Lotto a=new Lotto();
        
        a.setL1n1(l1n1);
        a.setL1n2(l1n2);
        a.setL1n3(l1n3);
        a.setL1n4(l1n4);
        a.setL1n5(l1n5);
       
        a.setL2n1(l2n1);
        a.setL2n2(l2n2);
        a.setL2n3(l2n3);
        a.setL2n4(l2n4);
        a.setL2n5(l2n5);
        
        a.setL3n1(l3n1);
        a.setL3n2(l3n2);
        a.setL3n3(l3n3);
        a.setL3n4(l3n4);
        a.setL3n5(l3n5);
        
        aList.add(a);
        
        count++;
        }
    }//GEN-LAST:event_AddActionPerformed

    private void upgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upgradeActionPerformed
        // TODO add your handling code here:
      
        listNum = 0;
      
        
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("Output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            ArrayList <Lotto> yList;
            yList = (ArrayList<Lotto>)oStream.readObject();
            
            listNum = Integer.parseInt(JOptionPane.showInputDialog(null,"You have already add "+yList.size()+" old input, Which one you want to upgrade? Please enter the numbers and click the 'OK' Button to continue!"));
            
                l1n1=yList.get(listNum-1).getL1n1();
                l1n1String=""+l1n1;
                jL1N1.setText(l1n1String);
                l1n2=yList.get(listNum-1).getL1n2();
                l1n2String=""+l1n2;
                jL1N2.setText(l1n2String);
                l1n3=yList.get(listNum-1).getL1n3();
                l1n3String=""+l1n3;
                jL1N3.setText(l1n3String);
                l1n4=yList.get(listNum-1).getL1n4();
                l1n4String=""+l1n4;
                jL1N4.setText(l1n4String);
                l1n5=yList.get(listNum-1).getL1n5();
                l1n5String=""+l1n5;
                jL1N5.setText(l1n5String);
                
                l2n1=yList.get(listNum-1).getL2n1();
                l2n1String=""+l2n1;
                jL2N1.setText(l2n1String);
                l2n2=yList.get(listNum-1).getL2n2();
                l2n2String=""+l2n2;
                jL2N2.setText(l2n2String);
                l2n3=yList.get(listNum-1).getL2n3();
                l2n3String=""+l2n3;
                jL2N3.setText(l2n3String);
                l2n4=yList.get(listNum-1).getL2n4();
                l2n4String=""+l2n4;
                jL2N4.setText(l2n4String);
                l2n5=yList.get(listNum-1).getL2n5();
                l2n5String=""+l2n5;
                jL2N5.setText(l2n5String);
                
                l3n1=yList.get(listNum-1).getL3n1();
                l3n1String=""+l3n1;
                jL3N1.setText(l3n1String);
                l3n2=yList.get(listNum-1).getL3n2();
                l3n2String=""+l3n2;
                jL3N2.setText(l3n2String);
                l3n3=yList.get(listNum-1).getL3n3();
                l3n3String=""+l3n3;
                jL3N3.setText(l3n3String);
                l3n4=yList.get(listNum-1).getL3n4();
                l3n4String=""+l3n4;
                jL3N4.setText(l3n4String);
                l3n5=yList.get(listNum-1).getL3n5();
                l3n5String=""+l3n5;
                jL3N5.setText(l3n5String);
                
                aList.remove(listNum-1);
                
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
            
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_upgradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LottoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LottoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LottoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LottoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LottoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Compareold;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jDrawNum;
    private javax.swing.JLabel jGoBack;
    private javax.swing.JLabel jL1;
    private javax.swing.JTextField jL1N1;
    private javax.swing.JTextField jL1N2;
    private javax.swing.JTextField jL1N3;
    private javax.swing.JTextField jL1N4;
    private javax.swing.JTextField jL1N5;
    private javax.swing.JLabel jL2;
    private javax.swing.JTextField jL2N1;
    private javax.swing.JTextField jL2N2;
    private javax.swing.JTextField jL2N3;
    private javax.swing.JTextField jL2N4;
    private javax.swing.JTextField jL2N5;
    private javax.swing.JLabel jL3;
    private javax.swing.JTextField jL3N1;
    private javax.swing.JTextField jL3N2;
    private javax.swing.JTextField jL3N3;
    private javax.swing.JTextField jL3N4;
    private javax.swing.JTextField jL3N5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jLine1;
    private javax.swing.JTextField jLine2;
    private javax.swing.JTextField jLine3;
    private javax.swing.JLabel jLotto;
    private javax.swing.JTextField jMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jResult;
    private javax.swing.JButton jSubmit;
    private javax.swing.JLabel jTitle;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton upgrade;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
