/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author x14105586
 */
public class LottoPlusGUI extends javax.swing.JFrame {

    private int num1, num2, num3, num4, num5, SecretLotto[], SecretLottoPlus1[], SecretLottoPlus2[], count1, count2, count3, count, listNum;
    private String num1String, num2String, num3String, num4String, num5String, Game;
    private ArrayList <LottoPlus> aList;
  
    public LottoPlusGUI() {
        initComponents();
        count = 0;
        SecretLotto = new int[5];
        SecretLottoPlus1 = new int[5];
        SecretLottoPlus2 = new int[5];
        aList = new ArrayList<>();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jGameTitle = new javax.swing.JLabel();
        jGameName = new javax.swing.JLabel();
        jNum = new javax.swing.JLabel();
        jSubmit = new javax.swing.JButton();
        jN1 = new javax.swing.JTextField();
        jN2 = new javax.swing.JTextField();
        jN3 = new javax.swing.JTextField();
        jN4 = new javax.swing.JTextField();
        jN5 = new javax.swing.JTextField();
        jGamecb = new javax.swing.JComboBox<>();
        jGameField = new javax.swing.JTextField();
        jDrawNum = new javax.swing.JTextField();
        jResult = new javax.swing.JTextField();
        jBackButton = new javax.swing.JButton();
        jGoBack = new javax.swing.JLabel();
        jLotto = new javax.swing.JLabel();
        jLottoPlus = new javax.swing.JLabel();
        jMessage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        save = new javax.swing.JButton();
        View = new javax.swing.JButton();
        compare = new javax.swing.JButton();
        upgrade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setBounds(new java.awt.Rectangle(715, 515, 515, 515));
        setLocation(new java.awt.Point(100, 100));
        setMinimumSize(new java.awt.Dimension(715, 515));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(715, 515));
        jPanel1.setMinimumSize(new java.awt.Dimension(715, 515));
        jPanel1.setPreferredSize(new java.awt.Dimension(715, 515));

        jGameTitle.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jGameTitle.setForeground(new java.awt.Color(204, 204, 255));
        jGameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jGameTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/lottoimg.gif"))); // NOI18N

        jGameName.setBackground(new java.awt.Color(0, 0, 0));
        jGameName.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jGameName.setText("Please select your draw");

        jNum.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jNum.setText("Please enter your numbers");

        jSubmit.setBackground(new java.awt.Color(51, 102, 255));
        jSubmit.setText("Submit");
        jSubmit.setBorder(null);
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });

        jN1.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jN1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jN2.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jN2ActionPerformed(evt);
            }
        });

        jN3.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jN3ActionPerformed(evt);
            }
        });

        jN4.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jN4ActionPerformed(evt);
            }
        });

        jN5.setBorder(new javax.swing.border.SoftBevelBorder(1));
        jN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jN5ActionPerformed(evt);
            }
        });

        jGamecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Lotto", "Lotto Plus 1", "Lotto Plus 2", " " }));
        jGamecb.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 102, 255)));
        jGamecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGamecbActionPerformed(evt);
            }
        });

        jGameField.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jGameField.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));

        jDrawNum.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jDrawNum.setBorder(null);
        jDrawNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDrawNumActionPerformed(evt);
            }
        });

        jResult.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jResult.setBorder(null);

        jBackButton.setBackground(new java.awt.Color(255, 255, 255));
        jBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/backlottoplus.png"))); // NOI18N
        jBackButton.setBorder(null);
        jBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBackButton.setFocusPainted(false);
        jBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonActionPerformed(evt);
            }
        });

        jGoBack.setFont(new java.awt.Font("Imprint MT Shadow", 0, 11)); // NOI18N
        jGoBack.setText("Go back");

        jLotto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/Lotto.png"))); // NOI18N

        jLottoPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/Lotto-plus-2.jpg"))); // NOI18N

        jMessage.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jMessage.setForeground(new java.awt.Color(255, 0, 0));
        jMessage.setBorder(null);

        add.setBackground(new java.awt.Color(51, 102, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(51, 102, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        View.setBackground(new java.awt.Color(51, 102, 255));
        View.setText("View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        compare.setBackground(new java.awt.Color(51, 102, 255));
        compare.setText("Compare");
        compare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareActionPerformed(evt);
            }
        });

        upgrade.setBackground(new java.awt.Color(51, 102, 255));
        upgrade.setText("Update");
        upgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upgradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGoBack)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jGameName)
                        .addGap(18, 18, 18)
                        .addComponent(jGamecb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jGameTitle)
                        .addGap(18, 18, 18)
                        .addComponent(jLotto)
                        .addGap(18, 18, 18)
                        .addComponent(jLottoPlus))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jNum)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jGameField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jN1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jN2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jN3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jN4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jN5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jDrawNum, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(compare)
                        .addGap(18, 18, 18)
                        .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(upgrade)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jGameTitle)
                            .addComponent(jGoBack)
                            .addComponent(jLotto, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBackButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLottoPlus)))
                .addGap(73, 73, 73)
                .addComponent(jMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGameName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGamecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jN5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDrawNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(View, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add)
                            .addComponent(save)
                            .addComponent(compare))))
                .addGap(34, 34, 34)
                .addComponent(upgrade)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
        // TODO add your handling code here:
        
        
        num1String = jN1.getText();
        num1 = Integer.parseInt(num1String);
        num2String = jN2.getText();
        num2 = Integer.parseInt(num2String);
        
        num3String = jN3.getText();
        num3 = Integer.parseInt(num3String);

        num4String = jN4.getText();
        num4 = Integer.parseInt(num4String);
       
        num5String = jN5.getText();
        num5 = Integer.parseInt(num5String);
        
        Game = (String)jGamecb.getSelectedItem();

        count1 = 0;
        count2 = 0;
        count3 = 0;
        
        if(num1==num2){
            jMessage.setText("Please do not enter the same number!");
        }
        else if(num3==num2||num3==num1){
            jMessage.setText("Please do not enter the same number!");
        }
        else if(num4==num3||num4==num2||num4==num1){
            jMessage.setText("Please do not enter the same number!");
        }
        else if(num5==num4||num5==num3||num5==num2||num5==num1){
            jMessage.setText("Please do not enter the same number!");
        }
        else{
        
outer:      for(int i=0; i<5; i++){
            SecretLotto[i]=(int)(Math.random()*40+1);
            for(int j=0; j<i; j++){
                if(SecretLotto[i]==SecretLotto[j]){
                    i--;
                    continue outer;
                }
            }
        }

outer:      for(int i=0; i<5; i++){
            SecretLottoPlus1[i]=(int)(Math.random()*40+1);
            for(int j=0; j<i; j++){
                if(SecretLottoPlus1[i]==SecretLottoPlus1[j]){
                    i--;
                    continue outer;
                }
            }
        }
outer:      for(int i=0; i<5; i++){
            SecretLottoPlus2[i]=(int)(Math.random()*40+1);
            for(int j=0; j<i; j++){
                if(SecretLottoPlus2[i]==SecretLottoPlus2[j]){
                    i--;
                    continue outer;
                }
            }
        }

        
        if(Game.equals("Lotto")){ 
            
            for( int i=0; i<5; i++){
                if( num1 == SecretLotto[i] || num2 == SecretLotto[i] || num3 == SecretLotto[i] || num4 == SecretLotto[i] || num5 == SecretLotto[i]){
                    count1++;
                
                }
            }
            
            jDrawNum.setText("The draw numbers were: "+ Arrays.toString(SecretLotto));
            
            for(int i=0;i<4;i++){
                if(count1==2){
                    jResult.setText("congratulations! You win €1,000, you matched "+count1);

                }
                else if(count1==3){
                    jResult.setText("congratulations! You win €10,000, you matched "+count1);

                }
                else if(count1==4){
                    jResult.setText("congratulations! You win €100,000, you matched "+count1);

                }
                else if(count1==5){
                    jResult.setText("congratulations! You win €1,000,000, you matched "+count1);

                }

                else{
                    jResult.setText("No prizes this time, you matched "+count1+", please try again");
                }
            }
            jMessage.setText("Click the green arrow at the corner of the screen to play again!");
        }
        else if(Game.equals("Lotto Plus 1")){
            
            for( int i=0; i<5; i++){
                if( num1 == SecretLottoPlus1[i] || num2 == SecretLottoPlus1[i] || num3 == SecretLottoPlus1[i] || num4 == SecretLottoPlus1[i] || num5 == SecretLottoPlus1[i]){
                    count2++;
                
                }
            }
            jDrawNum.setText("The draw numbers were: "+ Arrays.toString(SecretLottoPlus1));
            for(int i=0;i<4;i++){
                if(count2==2){
                    jResult.setText("congratulations! You win €500, you matched "+count2);

                }
                else if(count2==3){
                    jResult.setText("congratulations! You win €5,000, you matched "+count2);

                }
                else if(count2==4){
                    jResult.setText("congratulations! You win €50,000, you matched "+count2);

                }
                else if(count2==5){
                    jResult.setText("congratulations! You win €500,000, you matched "+count2);

                }
                

                else{
                    jResult.setText("No prizes this time, you matched "+count2+", please try again");
                }
                
            }
            jMessage.setText("Click the green arrow at the corner of the screen to play again!");
        }
        else if(Game.equals("Lotto Plus 2")){
            
            for( int i=0; i<5; i++){
                if( num1 == SecretLottoPlus2[i] || num2 == SecretLottoPlus2[i] || num3 == SecretLottoPlus2[i] || num4 == SecretLottoPlus2[i] || num5 == SecretLottoPlus2[i]){
                    count3++;
                }
            }
            jDrawNum.setText("The draw numbers were: "+ Arrays.toString(SecretLottoPlus2));
            for(int i=0;i<4;i++){
                if(count3==2){
                    jResult.setText("congratulations! You win 5 scratch cards, you matched "+count3);

                }
                else if(count3==3){
                    jResult.setText("congratulations! You win €500, you matched "+count3);

                }
                else if(count3==4){
                    jResult.setText("congratulations! You win €5,000, you matched "+count3);

                }
                else if(count3==5){
                    jResult.setText("congratulations! You win €50,000, you matched "+count3);

                }

                else{
                    jResult.setText("No prizes this time, you matched "+count3+", please try again");
                }
            }
            jMessage.setText("Click the green arrow at the corner of the screen to play again!");
        }
        else{
            
            jMessage.setText("You did not select a draw or did not enter the numbers correctly, try again!");
            
        }
        }
        
        
        
    }//GEN-LAST:event_jSubmitActionPerformed

    private void jGamecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGamecbActionPerformed
        // TODO add your handling code here:
        String Game = (String)jGamecb.getSelectedItem();
        jGameField.setText(""+Game);
        
    }//GEN-LAST:event_jGamecbActionPerformed

    private void jDrawNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDrawNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDrawNumActionPerformed

    private void jBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DrawSelectGUI().setVisible(true);
    }//GEN-LAST:event_jBackButtonActionPerformed

    private void jN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jN2ActionPerformed
        // TODO add your handling code here:
        /*int num1, num2, num3, num4, num5, SecretLotto[], SecretLottoPlus1[], SecretLottoPlus2[], count1, count2, count3;
        String num1String, num2String, num3String, num4String, num5String, Game;
        num1String = jN1.getText();
        num1 = Integer.parseInt(num1String);
        num2String = jN2.getText();
        num2 = Integer.parseInt(num2String);
        if(num1==num2){
            jLabel1.setText("Please enter the different number again");
        }*/
    }//GEN-LAST:event_jN2ActionPerformed

    private void jN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jN3ActionPerformed
        // TODO add your handling code here:
        /*int num1, num2, num3, num4, num5, SecretLotto[], SecretLottoPlus1[], SecretLottoPlus2[], count1, count2, count3;
        String num1String, num2String, num3String, num4String, num5String, Game;
        
        num1String = jN1.getText();
        num1 = Integer.parseInt(num1String);
        num2String = jN2.getText();
        num2 = Integer.parseInt(num2String);
        if(num1==num2){
            jLabel1.setText("Please enter the different number again");
            num2String = jN2.getText();
            num2 = Integer.parseInt(num2String);
        }
        num3String = jN3.getText();
        num3 = Integer.parseInt(num3String);
        if(num3==num2||num3==num1){
            jLabel1.setText("Please enter the different number again");
        }*/
    }//GEN-LAST:event_jN3ActionPerformed

    private void jN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jN4ActionPerformed
        // TODO add your handling code here:
        /*int num1, num2, num3, num4, num5, SecretLotto[], SecretLottoPlus1[], SecretLottoPlus2[], count1, count2, count3;
        String num1String, num2String, num3String, num4String, num5String, Game;
        
        num1String = jN1.getText();
        num1 = Integer.parseInt(num1String);
        num2String = jN2.getText();
        num2 = Integer.parseInt(num2String);
        if(num1==num2){
            jLabel1.setText("Please enter the different number again");
            num2String = jN2.getText();
            num2 = Integer.parseInt(num2String);
        }
        num3String = jN3.getText();
        num3 = Integer.parseInt(num3String);
        if(num3==num2||num3==num1){
            jLabel1.setText("Please enter the different number again");
            num3String = jN3.getText();
            num3 = Integer.parseInt(num3String);
        }
        num4String = jN4.getText();
        num4 = Integer.parseInt(num4String);
        if(num4==num3||num4==num2||num4==num1){
            jLabel1.setText("Please enter the different number again");
        }*/
    }//GEN-LAST:event_jN4ActionPerformed

    private void jN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jN5ActionPerformed
        // TODO add your handling code here:
        /*int num1, num2, num3, num4, num5, SecretLotto[], SecretLottoPlus1[], SecretLottoPlus2[], count1, count2, count3;
        String num1String, num2String, num3String, num4String, num5String, Game;
        
        num1String = jN1.getText();
        num1 = Integer.parseInt(num1String);
        num2String = jN2.getText();
        num2 = Integer.parseInt(num2String);
        if(num1==num2){
            jLabel1.setText("Please enter the different number again");
            num2String = jN2.getText();
            num2 = Integer.parseInt(num2String);
        }
        num3String = jN3.getText();
        num3 = Integer.parseInt(num3String);
        if(num3==num2||num3==num1){
            jLabel1.setText("Please enter the different number again");
            num3String = jN3.getText();
            num3 = Integer.parseInt(num3String);
        }
        num4String = jN4.getText();
        num4 = Integer.parseInt(num4String);
        if(num4==num3||num4==num2||num4==num1){
            jLabel1.setText("Please enter the different number again");
            num4String = jN4.getText();
            num4 = Integer.parseInt(num4String);
        }
        num5String = jN5.getText();
        num5 = Integer.parseInt(num5String);
        if(num5==num4||num5==num3||num5==num2||num5==num1){
            jLabel1.setText("Please enter the different number again");
            
        }*/
    }//GEN-LAST:event_jN5ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here
        num1String = jN1.getText();
        num2String = jN2.getText();
        num3String = jN3.getText();
        num4String = jN4.getText();
        num5String = jN5.getText();
        
        num1 = Integer.parseInt(num1String);
        num2 = Integer.parseInt(num2String);
        num3 = Integer.parseInt(num3String);
        num4 = Integer.parseInt(num4String);
        num5 = Integer.parseInt(num5String);
        
        if(num1==num2){
            jMessage.setText("Please do not enter the same number!");
        }
        else if(num3==num2||num3==num1){
            jMessage.setText("Please do not enter the same number!");
        }
        else if(num4==num3||num4==num2||num4==num1){
            jMessage.setText("Please do not enter the same number!");
        }
        else if(num5==num4||num5==num3||num5==num2||num5==num1){
            jMessage.setText("Please do not enter the same number!");
        }
        else{
        
        LottoPlus a = new LottoPlus();
        
        a.setNum1(num1);
        a.setNum2(num2);
        a.setNum3(num3);
        a.setNum4(num4);
        a.setNum5(num5);
        
        aList.add(a);
        
        count++;
        }
    }//GEN-LAST:event_addActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        File OutFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            OutFile= new File("Output1.data");
            fStream= new FileOutputStream(OutFile);
            oStream=new ObjectOutputStream(fStream);
            
            oStream.writeObject(aList);
            
            JOptionPane.showMessageDialog(null,"File written successfully.");
            
            oStream.close();
            }
            catch(IOException e){
                System.out.println(e);
            }
    }//GEN-LAST:event_saveActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("Output1.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            ArrayList <LottoPlus> yList;
            yList = (ArrayList<LottoPlus>)oStream.readObject();
            for(LottoPlus y:yList){
                    JOptionPane.showMessageDialog(null,"Line1: "+y.getNum1()+", "+y.getNum2()+", "+y.getNum3()+", "+y.getNum4()+", "+y.getNum5());
                }
            
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
            
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_ViewActionPerformed

    private void compareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareActionPerformed
        // TODO add your handling code here:
        count1 = 0;
        count2 = 0;
        count3 = 0;
        listNum = 0;
        Game = (String)jGamecb.getSelectedItem();
        
        outer:      for(int i=0; i<5; i++){
            SecretLotto[i]=(int)(Math.random()*40+1);
            for(int j=0; j<i; j++){
                if(SecretLotto[i]==SecretLotto[j]){
                    i--;
                    continue outer;
                }
            }
        }

outer:      for(int i=0; i<5; i++){
            SecretLottoPlus1[i]=(int)(Math.random()*40+1);
            for(int j=0; j<i; j++){
                if(SecretLottoPlus1[i]==SecretLottoPlus1[j]){
                    i--;
                    continue outer;
                }
            }
        }
outer:      for(int i=0; i<5; i++){
            SecretLottoPlus2[i]=(int)(Math.random()*40+1);
            for(int j=0; j<i; j++){
                if(SecretLottoPlus2[i]==SecretLottoPlus2[j]){
                    i--;
                    continue outer;
                }
            }
        }

        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("Output1.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            ArrayList <LottoPlus> yList;
            yList = (ArrayList<LottoPlus>)oStream.readObject();
            
            listNum = Integer.parseInt(JOptionPane.showInputDialog(null,"You have already add "+yList.size()+" old input, Which one you want to choose? Please enter the number and click the 'OK' Button to continue!"));
            if(Game.equals("Lotto")){ 
            
            for( int i=0; i<5; i++){
                if( yList.get(listNum-1).getNum1() == SecretLotto[i] || yList.get(listNum-1).getNum2() == SecretLotto[i] || yList.get(listNum-1).getNum3() == SecretLotto[i] || yList.get(listNum-1).getNum4() == SecretLotto[i] || yList.get(listNum-1).getNum5() == SecretLotto[i]){
                    count1++;
                
                }
            }
            
            jDrawNum.setText("The draw numbers were: "+ Arrays.toString(SecretLotto));
            
            for(int i=0;i<4;i++){
                if(count1==2){
                    jResult.setText("congratulations! You win €1,000, you matched "+count1);

                }
                else if(count1==3){
                    jResult.setText("congratulations! You win €10,000, you matched "+count1);

                }
                else if(count1==4){
                    jResult.setText("congratulations! You win €100,000, you matched "+count1);

                }
                else if(count1==5){
                    jResult.setText("congratulations! You win €1,000,000, you matched "+count1);

                }

                else{
                    jResult.setText("No prizes this time, you matched "+count1+", please try again");
                }
            }
            jMessage.setText("Click the green arrow at the corner of the screen to play again!");
        }
        else if(Game.equals("Lotto Plus 1")){
            
            for( int i=0; i<5; i++){
                if( yList.get(listNum-1).getNum1() == SecretLottoPlus1[i] || yList.get(listNum-1).getNum2() == SecretLottoPlus1[i] || yList.get(listNum-1).getNum3() == SecretLottoPlus1[i] || yList.get(listNum-1).getNum4() == SecretLottoPlus1[i] || yList.get(listNum-1).getNum5() == SecretLottoPlus1[i]){
                    count2++;
                
                }
            }
            jDrawNum.setText("The draw numbers were: "+ Arrays.toString(SecretLottoPlus1));
            for(int i=0;i<4;i++){
                if(count2==2){
                    jResult.setText("congratulations! You win €500, you matched "+count2);

                }
                else if(count2==3){
                    jResult.setText("congratulations! You win €5,000, you matched "+count2);

                }
                else if(count2==4){
                    jResult.setText("congratulations! You win €50,000, you matched "+count2);

                }
                else if(count2==5){
                    jResult.setText("congratulations! You win €500,000, you matched "+count2);

                }
                

                else{
                    jResult.setText("No prizes this time, you matched "+count2+", please try again");
                }
                
            }
            jMessage.setText("Click the green arrow at the corner of the screen to play again!");
        }
        else if(Game.equals("Lotto Plus 2")){
            
            for( int i=0; i<5; i++){
                if( yList.get(listNum-1).getNum1() == SecretLottoPlus2[i] || yList.get(listNum-1).getNum2() == SecretLottoPlus2[i] || yList.get(listNum-1).getNum3() == SecretLottoPlus2[i] || yList.get(listNum-1).getNum4() == SecretLottoPlus2[i] || yList.get(listNum-1).getNum5() == SecretLottoPlus2[i]){
                    count3++;
                }
            }
            jDrawNum.setText("The draw numbers were: "+ Arrays.toString(SecretLottoPlus2));
            for(int i=0;i<4;i++){
                if(count3==2){
                    jResult.setText("congratulations! You win 5 scratch cards, you matched "+count3);

                }
                else if(count3==3){
                    jResult.setText("congratulations! You win €500, you matched "+count3);

                }
                else if(count3==4){
                    jResult.setText("congratulations! You win €5,000, you matched "+count3);

                }
                else if(count3==5){
                    jResult.setText("congratulations! You win €50,000, you matched "+count3);

                }

                else{
                    jResult.setText("No prizes this time, you matched "+count3+", please try again");
                }
            }
            jMessage.setText("Click the green arrow at the corner of the screen to play again!");
        }
        else{
            
            jMessage.setText("You did not select a draw or did not enter the numbers correctly, try again!");
            
        }
            
        oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
            
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_compareActionPerformed

    private void upgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upgradeActionPerformed
        // TODO add your handling code here:
        count1 = 0;
        count2 = 0;
        count3 = 0;
        listNum = 0;
        Game = (String)jGamecb.getSelectedItem();
        
  

        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("Output1.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            ArrayList <LottoPlus> yList;
            yList = (ArrayList<LottoPlus>)oStream.readObject();
            
            listNum = Integer.parseInt(JOptionPane.showInputDialog(null,"You have already add "+yList.size()+" old input, Which one you want to upgrade? Please enter the number and click the 'OK' Button to continue!"));
            
            num1 = yList.get(listNum-1).getNum1();
            num1String = "" + num1;
            jN1.setText(num1String);
            
            num2 = yList.get(listNum-1).getNum2();
            num2String = "" + num2;
            jN2.setText(num2String);
            
            num3 = yList.get(listNum-1).getNum3();
            num3String = "" + num3;
            jN3.setText(num3String);
            
            num4 = yList.get(listNum-1).getNum4();
            num4String = "" + num4;
            jN4.setText(num4String);
            
            num5 = yList.get(listNum-1).getNum5();
            num5String = "" + num5;
            jN5.setText(num5String);
            
            aList.remove(listNum-1);
           
            
        oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
            
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_upgradeActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LottoPlus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LottoPlus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LottoPlus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LottoPlus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
*/
        /* Create and display the form */
   /*     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LottoPlus().setVisible(true);
            }
        });
        
 */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton View;
    private javax.swing.JButton add;
    private javax.swing.JButton compare;
    private javax.swing.JButton jBackButton;
    private javax.swing.JTextField jDrawNum;
    private javax.swing.JTextField jGameField;
    private javax.swing.JLabel jGameName;
    private javax.swing.JLabel jGameTitle;
    private javax.swing.JComboBox<String> jGamecb;
    private javax.swing.JLabel jGoBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLotto;
    private javax.swing.JLabel jLottoPlus;
    private javax.swing.JTextField jMessage;
    private javax.swing.JTextField jN1;
    private javax.swing.JTextField jN2;
    private javax.swing.JTextField jN3;
    private javax.swing.JTextField jN4;
    private javax.swing.JTextField jN5;
    private javax.swing.JLabel jNum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jResult;
    private javax.swing.JButton jSubmit;
    private javax.swing.JButton save;
    private javax.swing.JButton upgrade;
    // End of variables declaration//GEN-END:variables
}
